export const FETCH_CARDS = "FETCH_CARDS";
export const FETCH_METADATA = "FETCH_METADATA";
export const SEARCH_TERM = "SEARCH_TERM";
export const SELECTED_CLASS = "SELECTED_CLASS";
export const SELECTED_RARITY = "SELECTED_RARITY";
export const COUNT_CARDS = "COUNT_CARDS";
